openapi: 3.0.1
info:
  title: HubSpot CRM API
  description: 'Allows an app to extend the CRM UI by surfacing custom cards in the sidebar of record pages. These cards are defined up-front as part of app configuration, then populated by external data fetch requests when the record page is accessed by a user.'
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
servers:
  - url: https://api.hubapi.com
tags:
  - name: Basic
paths:
  /crm/v3/objects/contacts:
    post:
      tags:
        - Basic
      summary: Post
      description: Create a contact with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard contacts are provided.
      operationId: contacts
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write

  /crm/v3/objects/contacts/{contactId}:
    delete:
      tags:
        - Basic
      summary: Delete
      description: Move an Object identified by `{contactId}` to the recycling bin.
      operationId: contacts
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
    patch:
      tags:
        - "Basic"
      summary: Patch
      description: "Perform a partial update of an Object identified by `{contactId}`. `{contactId}` refers to the internal object ID. Provided property values will be overwritten. Read-only and non-existent properties result in an error. Properties values can be cleared by passing an empty string."
      operationId: contacts
      security:
        - oauth2:
            - "crm.objects.contacts.write"
        - private_apps:
            - "crm.objects.contacts.write"
    get:
      tags:
        - Basic
      summary: Get
      description: Read an Object identified by `{contactId}`and `{emailId}`. It refers to the internal object ID.
      operationId: contacts
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
  /crm/v3/objects/contacts/search:
    post:
      tags:
        - Basic
      summary: Query
      description: a contacts search will return createDate, email, firstname, hs_object_id, lastModifiedDate, and lastname by default. To return a specific set of properties, include a properties array in the request body.
      operationId: contacts
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
  /crm/v3/objects/companies:
    post:
      tags:
        - Basic
      summary: Post
      description: Create a company with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard companies is provided.
      operationId: companies
      security:
        - oauth2:
            - "crm.objects.companies.write"
        - private_apps:
            - "crm.objects.companies.write"
  /crm/v3/objects/companies/{companyId}:
    delete:
      tags:
        - Basic
      summary: Delete
      description: Move an Object identified by `{companyId}` to the recycling bin.
      operationId: companies
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
    patch:
      tags:
        - Basic
      summary: Patch
      description: >
        Perform a partial update of an Object identified by `{companyId}`or optionally a unique property value as specified by the `idProperty` query param. `{companyId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.
      operationId: companies
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
    get:
      tags:
        - Basic
      summary: GET
      description: Read an Object identified by `{companyId}`. `{companyId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: companies
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
  /crm/v3/objects/companies/search:
    post:
      tags:
        - Basic
      summary: Query
      description: a companies search will return createDate, domain, hs_object_id, lastModifiedDate, and name by default. To return a specific set of properties, include a properties array in the request body.
      operationId: companies
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
  /crm/v3/objects/tickets:
    post:
      tags:
        - Basic
      summary: Post
      description: Create a ticket with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard tickets is provided.
      operationId: tickets
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets
  /crm/v3/objects/tickets/{ticketId}:
    delete:
      tags:
        - Basic
      summary: Delete
      description: Move an Object identified by `{ticketId}` to the recycling bin.
      operationId: tickets
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets
    patch:
      tags:
        - Basic
      summary: Patch
      description: Perform a partial update of an Object identified by {ticketId}or optionally a unique property value as specified by the idProperty query param. {ticketId} refers to the internal object ID by default, and the idProperty query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.
      operationId: tickets
      security:
        - oauth2:
            - tickets
        - private_apps:
            - tickets
    get:
      tags:
        - Basic
      summary: GET
      description: Read an Object identified by {ticketId}. {ticketId} refers to the internal object ID by default, or optionally any unique property value as specified by the idProperty query param. Control what is returned via the properties query param.
      operationId: tickets
      security:
        - oauth2:
            - tickets
        - private_apps:
            - tickets
  /crm/v3/objects/tickets/search:
    post:
      tags:
        - Basic
      summary: Query
      description: a contacts search will return content, hs_pipeline, hs_pipeline_stage,hs_ticket_category, hs_ticket_priority, subject,createDate, hs_lastModifiedDate, hs_object_id. To return a specific set of properties, include a properties array in the request body.
      operationId: tickets
      security:
        - oauth2:
            - tickets
        - private_apps:
            - tickets
  /crm/v3/objects/deals:
    post:
      tags:
        - Basic
      summary: Post
      description: Create a deal with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard deals is provided.
      operationId: deals
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
  /crm/v3/objects/deals/{dealId}:
    delete:
      tags:
        - Basic
      summary: Delete
      description: Move an Object identified by `{dealId}` to the recycling bin.
      operationId: deals
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
    patch:
      tags:
        - Basic
      summary: Patch
      description: >
        Perform a partial update of an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
      operationId: deals
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
    get:
      tags:
        - Basic
      summary: GET
      description: Read an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Control what is returned via the `properties` query param.
      operationId: deals
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
  /crm/v3/objects/deals/search:
    post:
      tags:
        - Basic
      summary: QUERY
      description: a deals search will return dealName, amount, closeDate, pipeline,dealsTage, createDate, hsLastModifiedDate, hs_object_id. To return a specific set of properties, include a properties array in the request body.
      operationId: deals
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
  /crm/v3/objects/goal_targets/{goalTargetId}:
    get:
      tags:
        - Basic
      summary: GET
      description: Read an Object identified by `{goalTargetId}`. `{goalTargetId}` refers to the internal object ID by default.
      operationId: goals
      security:
        - oauth2:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.goals.read
  /crm/v3/objects/goal_targets/search:
    post:
      tags:
        - Basic
      summary: QUERY
      description: a goals search will return hsCreateDate, hsLastModifiedDate, hs_object_id. To return a specific set of properties, include a properties array in the request body.
      operationId: goals
      security:
        - oauth2:
            - crm.objects.goals.read
        - private_apps:
            - crm.objects.goals.read
components:
  securitySchemes:
    oauth2_legacy:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            crm.objects.custom.read: View custom object records
            tickets: Read and write tickets
            crm.objects.goals.read: Read goals
            media_bridge.read: Read media and media events
            crm.objects.custom.write: Change custom object records
            e-commerce: e-commerce

    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            crm.objects.companies.read: ''
            crm.objects.companies.write: ''
            crm.objects.contacts.read: ''
            crm.objects.contacts.write: ''
            crm.objects.deals.read: ''
            crm.objects.deals.write: ''

    private_apps_legacy:
      type: apiKey
      name: private-app-legacy
      in: header

    private_apps:
      type: apiKey
      name: private-app
      in: header

x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Ruby
  - Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE